services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  api-mock:
    build:
      context: .
      dockerfile: docker/api-mock/Dockerfile
    ports:
      - "4010:4010"
    volumes:
      - ./docs:/app/docs

volumes:
  frontend_node_modules:
