/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить профиль владельца календаря. */
        get: operations["OwnerApi_getOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Предстоящие бронирования всех типов событий. */
        get: operations["OwnerApi_listUpcomingBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner/bookings/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить детали одного бронирования. */
        get: operations["OwnerApi_getBookingById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner/bookings/{bookingId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Отменить бронирование (владелец). */
        post: operations["OwnerApi_cancelBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список типов событий владельца. */
        get: operations["OwnerApi_listOwnerEventTypes"];
        put?: never;
        /** @description Создать тип события. */
        post: operations["OwnerApi_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Обновить тип события (partial update). */
        patch: operations["OwnerApi_updateEventType"];
        trace?: never;
    };
    "/public/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создать бронирование.
         *     endAt вычисляется сервером по durationMinutes выбранного event type.
         *     409 если интервал пересекается с существующим бронированием
         *     (даже другого типа события).
         */
        post: operations["PublicApi_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/bookings/by-token/{guestCancelToken}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить бронирование гостя по токену. */
        get: operations["PublicApi_getBookingByGuestToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/bookings/by-token/{guestCancelToken}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Отменить бронирование гостя по токену. */
        post: operations["PublicApi_cancelBookingByGuestToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Публичный список доступных типов событий. */
        get: operations["PublicApi_listPublicEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Слоты для выбранного типа события в заданном диапазоне.
         *     Правило занятости общее для всего календаря.
         *     timezone — IANA timezone гостя, используется для группировки слотов по дням.
         */
        get: operations["PublicApi_listAvailableSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Booking: {
            id: string;
            eventTypeId: string;
            eventTypeName: components["schemas"]["NonEmptyString"];
            startAt: components["schemas"]["UtcDateTime"];
            endAt: components["schemas"]["UtcDateTime"];
            guestName: components["schemas"]["NonEmptyString"];
            guestEmail: components["schemas"]["NonEmptyString"];
            createdAt: components["schemas"]["UtcDateTime"];
            /** @enum {string} */
            status: "active" | "cancelled";
        };
        /**
         * @description Правило занятости слота:
         *
         *     Нельзя создать два активных бронирования на пересекающиеся интервалы,
         *     даже если они относятся к разным типам событий.
         *
         *     Конфликт определяется как:
         *       existing.startAt < new.endAt AND existing.endAt > new.startAt
         *
         *     Примеры:
         *       10:00–10:30 и 10:00–10:30 → конфликт
         *       10:00–10:30 и 10:15–10:45 → конфликт
         *       10:00–10:30 и 10:30–11:00 → допустимо (смежные, не пересекаются)
         *
         *     При проверке конфликтов учитываются только бронирования со статусом "active".
         */
        BookingConflictRuleDoc: Record<string, never>;
        BookingCreateInput: {
            eventTypeId: string;
            startAt: components["schemas"]["UtcDateTime"];
            guestName: components["schemas"]["NonEmptyString"];
            guestEmail: components["schemas"]["NonEmptyString"];
        };
        /**
         * @description Правило вычисления endAt:
         *
         *     Клиент передает только startAt и eventTypeId.
         *     Сервер обязан:
         *       1. загрузить EventType,
         *       2. взять durationMinutes,
         *       3. вычислить endAt = startAt + durationMinutes.
         *
         *     Клиент не может передавать endAt при создании бронирования.
         */
        BookingEndAtComputationDoc: Record<string, never>;
        BookingListResponse: {
            items: components["schemas"]["Booking"][];
            meta: components["schemas"]["PaginatedMeta"];
        };
        ConflictErrorResponse: {
            /** @enum {string} */
            code: "slot_conflict";
        } & WithRequired<components["schemas"]["ErrorResponse"], "code">;
        ErrorResponse: {
            code: components["schemas"]["NonEmptyString"];
            message: components["schemas"]["NonEmptyString"];
        };
        EventType: {
            id: string;
            name: components["schemas"]["NonEmptyString"];
            description?: string;
            durationMinutes: components["schemas"]["PositiveInt"];
        };
        EventTypeCreateInput: {
            name: components["schemas"]["NonEmptyString"];
            description?: string;
            durationMinutes: components["schemas"]["PositiveInt"];
        };
        EventTypeListResponse: {
            items: components["schemas"]["EventType"][];
        };
        EventTypeUpdateInput: {
            name?: components["schemas"]["NonEmptyString"];
            description?: string;
            durationMinutes?: components["schemas"]["PositiveInt"];
        };
        GuestBooking: {
            id: string;
            eventTypeId: string;
            eventTypeName: components["schemas"]["NonEmptyString"];
            startAt: components["schemas"]["UtcDateTime"];
            endAt: components["schemas"]["UtcDateTime"];
            guestName: components["schemas"]["NonEmptyString"];
            guestEmail: components["schemas"]["NonEmptyString"];
            createdAt: components["schemas"]["UtcDateTime"];
            /** @enum {string} */
            status: "active" | "cancelled";
            guestCancelToken: components["schemas"]["NonEmptyString"];
        };
        GuestBookingCreatedResponse: {
            booking: components["schemas"]["GuestBooking"];
        };
        /**
         * @description Правило гостевого доступа:
         *
         *     Для каждого созданного бронирования сервер генерирует guestCancelToken.
         *
         *     Токен позволяет гостю:
         *       - получить свое бронирование,
         *       - отменить свое бронирование,
         *
         *     без регистрации и авторизации.
         *
         *     В рамках учебного проекта guestCancelToken может возвращаться
         *     прямо в ответе на создание бронирования.
         */
        GuestCancelTokenRuleDoc: Record<string, never>;
        NonEmptyString: string;
        /** Format: int32 */
        NonNegativeInt: number;
        NotFoundErrorResponse: {
            /** @enum {string} */
            code: "not_found";
        } & WithRequired<components["schemas"]["ErrorResponse"], "code">;
        Owner: {
            id: string;
            name: string;
            timezone: components["schemas"]["NonEmptyString"];
        };
        PaginatedMeta: {
            total: components["schemas"]["NonNegativeInt"];
            limit: components["schemas"]["PositiveInt"];
            offset: components["schemas"]["NonNegativeInt"];
        };
        PaginationParams: {
            limit?: components["schemas"]["PositiveInt"];
            offset?: components["schemas"]["NonNegativeInt"];
        };
        /** Format: int32 */
        PositiveInt: number;
        Slot: {
            eventTypeId: string;
            startAt: components["schemas"]["UtcDateTime"];
            endAt: components["schemas"]["UtcDateTime"];
            isAvailable: boolean;
        };
        SlotListResponse: {
            items: components["schemas"]["Slot"][];
            meta: components["schemas"]["PaginatedMeta"];
        };
        /** Format: date-time */
        UtcDateTime: string;
        ValidationErrorResponse: {
            /** @enum {string} */
            code: "validation_error";
        } & WithRequired<components["schemas"]["ErrorResponse"], "code">;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    OwnerApi_getOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
    OwnerApi_listUpcomingBookings: {
        parameters: {
            query?: {
                from?: components["schemas"]["UtcDateTime"];
                limit?: components["schemas"]["PositiveInt"];
                offset?: components["schemas"]["NonNegativeInt"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingListResponse"];
                };
            };
        };
    };
    OwnerApi_getBookingById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
        };
    };
    OwnerApi_cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
        };
    };
    OwnerApi_listOwnerEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeListResponse"];
                };
            };
        };
    };
    OwnerApi_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreateInput"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    OwnerApi_updateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeUpdateInput"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
        };
    };
    PublicApi_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreateInput"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestBookingCreatedResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictErrorResponse"];
                };
            };
        };
    };
    PublicApi_getBookingByGuestToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guestCancelToken: components["schemas"]["NonEmptyString"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestBooking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
        };
    };
    PublicApi_cancelBookingByGuestToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guestCancelToken: components["schemas"]["NonEmptyString"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestBooking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
        };
    };
    PublicApi_listPublicEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeListResponse"];
                };
            };
        };
    };
    PublicApi_listAvailableSlots: {
        parameters: {
            query: {
                from: components["schemas"]["UtcDateTime"];
                to: components["schemas"]["UtcDateTime"];
                timezone?: components["schemas"]["NonEmptyString"];
                limit?: components["schemas"]["PositiveInt"];
                offset?: components["schemas"]["NonNegativeInt"];
            };
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotListResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
